[package]
name = "conference_scheduler_mysql"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "25.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.19"
